### ISSUE TITLE
关于数据集的sentiment distribution

### ISSUE THREAD

**Issue by messyidea** [laserwave/jst#1]
您好，请教下数据集中原始包含的sentiment distribution是怎么来的？手工标注还是使用其它的方法？
谢谢！

**Comment by laserwave** [comment]
来自爬取网页上的新闻数据，以及读者的情感投票，归一化得来

**Comment by messyidea** [comment]
哦，想起来了，以前网页新闻好像有感情投票的选项，现在貌似比较少了，新浪新闻也改版了。
谢谢～

**Comment by laserwave** [comment]
不客气~
